VoetbalTicketStore/Controllers/ShoppingCartController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Exceptions;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    [Authorize]
    public class ShoppingCartController : BaseController
    {

        private IBestellingService bestellingService;
        private IShoppingCartDataService shoppingCartDataService;
        private UserManager<ApplicationUser> userManager;


        public ShoppingCartController()
        {

        }

        public ShoppingCartController(IBestellingService bestellingService, IShoppingCartDataService shoppingCartDataService, UserManager<ApplicationUser> userManager)
        {
            this.bestellingService = bestellingService;
            this.shoppingCartDataService = shoppingCartDataService;
            this.userManager = userManager;
        }

        // GET: ShoppingCart
        public ActionResult Index()
        {
            if (TempData["error"] != null)
            {
                ViewBag.Error = TempData["error"].ToString();
            }
            if (TempData["success"] != null)
            {
                ViewBag.Success = TempData["success"].ToString();
            }

            // Openstaande bestelling ophalen
            if (bestellingService == null)
            {
                bestellingService = new BestellingService();
            }
            Bestelling bestelling = bestellingService.FindOpenstaandeBestellingDoorUser(User.Identity.GetUserId());

            // Lijst voor aantallen
            List<SelectListItem> list = new List<SelectListItem>
            {
                new SelectListItem { Text = "1", Value = "1" },
                new SelectListItem { Text = "2", Value = "2" },
                new SelectListItem { Text = "3", Value = "3" },
                new SelectListItem { Text = "4", Value = "4" }
            };

            // ViewModel aanmaken en opvullen
            ShoppingCart shoppingCart = null;
            if (bestelling != null)
            {
                shoppingCart = new ShoppingCart()
                {
                    Bestelling = bestelling,
                    ShoppingCartEntries = bestelling.ShoppingCartDatas.ToList(),
                    TotaalPrijs = bestellingService.BerekenTotaalPrijs(bestelling.ShoppingCartDatas),
                    HoeveelheidList = list
                };
                UpdateShoppingCartCounter(bestelling);
            }
            return View(shoppingCart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(TicketConfirm ticketConfirm)
        {
            try
            {
                if (ticketConfirm == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                // Nieuwe bestelling aanmaken indien nodig
                Bestelling bestelling = CreateNieuweBestellingIndienNodig();

                // ShoppingCartData toevoegen
                if (shoppingCartDataService == null)
                {
                    shoppingCartDataService = new ShoppingCartDataService();
                }
                shoppingCartDataService.AddToShoppingCart(bestelling.Id, ticketConfirm.Prijs, ticketConfirm.WedstrijdId, ticketConfirm.ThuisploegId, ticketConfirm.BezoekersId, ticketConfirm.AantalTickets, ticketConfirm.VakId, User.Identity.GetUserId());

                UpdateShoppingCartCounter(bestelling);

                // Success message meegeven
                SetSuccessfulAddMessage("Uw winkelwagentje werd aangepast!");
                // RedirectToAction ipv View, anders wordt geen model meegegeven!
                return RedirectToAction("Index");
            }
            catch (BestelException ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAbonnement(AbonnementBuy abonnementBuy)
        {
            if (abonnementBuy == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Nieuwe bestelling aanmaken indien nodig
            Bestelling bestelling = CreateNieuweBestellingIndienNodig();

            // ShoppingCartData toevoegen
            if (shoppingCartDataService == null)
            {
                shoppingCartDataService = new ShoppingCartDataService();
            }
            shoppingCartDataService.AddAbonnementToShoppingCart(bestelling.Id, abonnementBuy.Prijs, abonnementBuy.AantalAbonnementen, abonnementBuy.GeselecteerdVakId, abonnementBuy.PloegId, User.Identity.GetUserId());

            UpdateShoppingCartCounter(bestelling);

            // Success message meegeven
            SetSuccessfulAddMessage("Uw winkelwagentje werd aangepast!");

            return RedirectToAction("Index");
        }



        private Bestelling CreateNieuweBestellingIndienNodig()
        {
            if (bestellingService == null)
            {
                bestellingService = new BestellingService();
            }
            return bestellingService.CreateNieuweBestellingIndienNodig(User.Identity.GetUserId());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Remove(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (shoppingCartDataService == null)
            {
                shoppingCartDataService = new ShoppingCartDataService();
            }
            shoppingCartDataService.RemoveShoppingCartData(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdjustAmount(ShoppingCart shoppingCart)
        {
            if (shoppingCart == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // hoeveelheid aanpassen
            if (shoppingCartDataService == null)
            {
                shoppingCartDataService = new ShoppingCartDataService();
            }
            shoppingCartDataService.AdjustAmount(shoppingCart.SelectedShoppingCartData, shoppingCart.NieuweHoeveelheid);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Clear(ShoppingCart shoppingCart)
        {
            if (shoppingCart == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (shoppingCartDataService == null)
            {
                shoppingCartDataService = new ShoppingCartDataService();
            }
            // Bestelling deleten en dan de bestellijnen cascaden zou handig zijn, maar lukt niet aangezien de FK constraint voor de tickets dan overtreden wordt
            shoppingCartDataService.RemoveShoppingCartDataVanBestelling(shoppingCart.GeselecteerdeBestelling);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Finalise(ShoppingCart shoppingCart)
        {
            if (shoppingCart == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                // Plaats bestelling
                if (bestellingService == null)
                {
                    bestellingService = new BestellingService();
                }
                Bestelling bestelling = bestellingService.FindOpenstaandeBestellingDoorUser(User.Identity.GetUserId());
                bestellingService.PlaatsBestelling(bestelling, User.Identity.GetUserId());

                // Find & update user (meest favoriete team)

                if (userManager == null)
                {
                    userManager = new UserManager<ApplicationUser>(
                    new UserStore<ApplicationUser>(
                        new ApplicationDbContext()));
                }
                var user = userManager.FindById(User.Identity.GetUserId());
                int nieuwFavorietTeam = bestellingService.GetMeestGekochteThuisploeg(User.Identity.GetUserId());

                if (nieuwFavorietTeam != -1)
                {
                    user.FavorietTeam = nieuwFavorietTeam;
                    userManager.Update(user);
                }

                Session["ShoppingCartItemTotal"] = null;

            }
            catch (BestelException ex)
            {
                // Teveel tickets
                // Geen plaats meer

                // When you use redirection, you shall not use ViewBag, but TempData
                // TempData passes data between the current and next HTTP request
                TempData["error"] = ex.Message;
                return RedirectToAction("Index");
            }

            TempData["msg"] = "Uw bestelling werd succesvol afgerond!";
            return RedirectToAction("Index", "Bezoeker");
        }

        #region privates
        private void UpdateShoppingCartCounter(Bestelling bestelling)
        {
            int totaalAantalitems = 0;
            foreach (ShoppingCartData s in bestelling.ShoppingCartDatas)
            {
                totaalAantalitems += s.Hoeveelheid;
            }
            if (totaalAantalitems > 0)
            {
                Session["ShoppingCartItemTotal"] = totaalAantalitems;
            }
            else
            {
                Session["ShoppingCartItemTotal"] = null;
            }
        }

        private void SetSuccessfulAddMessage(string message)

VoetbalTicketStore/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.Service.Interfaces;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    [Authorize]
    public class TicketController : BaseController
    {

        private IWedstrijdService wedstrijdService;
        private IVakService vakService;

        public TicketController()
        {

        }

        public TicketController(IWedstrijdService wedstrijdService, IVakService vakService)
        {
            this.wedstrijdService = wedstrijdService;
            this.vakService = vakService;
        }

        // GET: Ticket
        public ActionResult Buy(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Wedstrijd ophalen
            if (wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            Wedstrijd wedstrijd = wedstrijdService.GetWedstrijdById(id);

            // Vakken ophalen van stadion

            if (vakService == null)
            {
                vakService = new VakService();
            }

            IEnumerable<Vak> vakken = vakService.GetVakkenInStadion(wedstrijd.Stadionid);

            // Prijzen bepalen per vak (thuisploeg)
            vakService.BerekenPrijzenBijVakken(vakken, wedstrijd.Club);

            // Vrije plaatsen bepalen per vak
            vakService.BerekenAantalVrijePlaatsen(vakken, wedstrijd, wedstrijd.Club);

            // ViewModel maken en opvullen
            TicketWedstrijd ticketWedstrijd = new TicketWedstrijd
            {
                Wedstrijd = wedstrijd,
                Stadion = wedstrijd.Stadion,
                Thuisploeg = wedstrijd.Club,
                Tegenstanders = wedstrijd.Club1,
                VakkenList = vakken
            };

            return View(ticketWedstrijd);
        }

        // POST: Confirm
        [HttpPost]
        public ActionResult Confirm(int vakId, int aantalVrijePlaatsen, decimal prijs, int wedstrijdId, int thuisploegId, int bezoekersId, string vakNaam)
        {

            if (vakId < 0 || aantalVrijePlaatsen < 0 || prijs < 0 || wedstrijdId < 0 || thuisploegId < 0 || bezoekersId < 0 || vakNaam == null || vakNaam.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            // Lijst voor aantal tickets
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "1", Value = "1", Selected = true });
            list.Add(new SelectListItem { Text = "2", Value = "2" });
            list.Add(new SelectListItem { Text = "3", Value = "3" });
            list.Add(new SelectListItem { Text = "4", Value = "4" });

            // ViewModel maken en opvullen
            TicketConfirm ticketConfirm = new TicketConfirm()
            {
                AantalVrijePlaatsen = aantalVrijePlaatsen,
                Prijs = prijs,
                HoeveelheidTicketsList = list,
                VakId = vakId,
                VakNaam = vakNaam,
                WedstrijdId = wedstrijdId,
                ThuisploegId = thuisploegId,
                BezoekersId = bezoekersId
            };

            return PartialView(ticketConfirm);
        }
    }
}

VoetbalTicketStore/Views/Ticket/Buy.cshtml
@model VoetbalTicketStore.ViewModel.TicketWedstrijd
@{
    ViewBag.Title = "Tickets kopen";
}
<hr />
<div class="row">
    <div class="col-md-6">
        @{
            var LogoThuisploeg = "/Content/img/clublogo/placeholder.png";
            var LogoBezoekers = "/Content/img/clublogo/placeholder.png";

            if (Model.Thuisploeg.Logo != null && Model.Tegenstanders.Logo != null)
            {
                LogoThuisploeg = Model.Thuisploeg.Logo;
                LogoBezoekers = Model.Tegenstanders.Logo;
            }
        }
        <img src="@LogoThuisploeg" class="wedstrijd" alt="@Model.Thuisploeg.Naam" />
        <img src="@LogoBezoekers" class="wedstrijd" alt="@Model.Tegenstanders.Naam" />
    </div>
    <div class="col-md-6">
        <h1>
            @Model.Thuisploeg.Naam - @Model.Tegenstanders.Naam
            <br />
            <small>@Model.Stadion.Naam</small>
            <br />
            <small>@Model.Wedstrijd.DatumEnTijd</small>
        </h1>
    </div>
</div>
<div class="row">
    <div id="partial">
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.LabelFor(modelItem => modelItem.VakkenList.First().VakType.Beschrijving)
                </th>
                <th>
                    @Html.LabelFor(modelItem => modelItem.VakkenList.First().BerekendePrijs)
                </th>
                <th>Plaatsen</th>
                <th></th>
            </tr>
            @foreach (var item in Model.VakkenList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.VakType.Beschrijving)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BerekendePrijs)
                    </td>
                    <td>
                        @if (item.AantalVrijePlaatsen <= 0)
                        {
                            <text>Geen tickets meer!</text>

                        }
                        else
                        {
                            <text>Nog</text> @Html.DisplayFor(modelItem => item.AantalVrijePlaatsen) <text>van de </text>@Html.DisplayFor(modelItem => item.MaximumAantalZitplaatsen) <text>plaatsen vrij!</text>
                        }

                    </td>
                    <td>
                        @if (item.AantalVrijePlaatsen <= 0)
                        {
                            <button type="button" class="btn btn-warning" disabled>Uitverkocht!</button>
                        }
                        else
                        {@*TODO: gevuld viewmodel in de ActionLink (RouteValues) steken*@
                        @Ajax.ActionLink("Bestel!", "Confirm", "Ticket", new { vakId = item.Id, aantalVrijePlaatsen = item.AantalVrijePlaatsen, prijs = item.BerekendePrijs, wedstrijdId = Model.Wedstrijd.Id, thuisploegId = Model.Thuisploeg.Id, bezoekersId = Model.Tegenstanders.Id, vakNaam = item.VakType.Beschrijving }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, htmlAttributes: new { @class = "btn btn-primary" })}
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

VoetbalTicketStore/Views/Ticket/Confirm.cshtml
@model VoetbalTicketStore.ViewModel.TicketConfirm

<ul class="list-group">
    <li class="list-group-item"><strong>Gekozen vak: </strong>@Html.DisplayFor(model => model.VakNaam)</li>
    <li class="list-group-item"><strong>Aantal vrije plaatsen in vak: </strong>@Html.DisplayFor(model => model.AantalVrijePlaatsen)</li>
    <li class="list-group-item"><strong>Prijs:</strong> @Html.DisplayFor(model => model.Prijs)</li>
    <li class="list-group-item">


        @using (Html.BeginForm("Add", "ShoppingCart", new VoetbalTicketStore.ViewModel.TicketConfirm { Prijs = Model.Prijs, VakId = Model.VakId, WedstrijdId = Model.WedstrijdId, ThuisploegId = Model.ThuisploegId, BezoekersId = Model.BezoekersId }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <strong>Aantal: </strong>@Html.DropDownListFor(a => a.AantalTickets, Model.HoeveelheidTicketsList)
            <hr />
            <button type="submit" class="btn btn-primary" role="menuitem">
                <i class="glyphicon glyphicon-plus"></i>Koop!
            </button>
        }
    </li>
</ul>

VoetbalTicketStore/Views/Ticket/Fail.cshtml
Buy failed....

VoetbalTicketStore/Views/Ticket/Success.cshtml
Buy succesful!

VoetbalTicketStore/Views/Ticket/TeveelTickets.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    Teveel tickets!
    </div>
</body>
</html>