VoetbalTicketStore/Controllers/AbonnementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.Service.Interfaces;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    public class AbonnementController : BaseController
    {


        private IVakService vakService;
        private IClubService clubService;

        public AbonnementController()
        {

        }

        public AbonnementController(IVakService vakService, IClubService clubService)
        {
            this.vakService = vakService;
            this.clubService = clubService;
        }

        [Authorize]
        // GET: Abonnement
        public ActionResult Buy(ClubOverview clubOverview)
        {
            if (clubOverview == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (vakService == null)
            {
                vakService = new VakService();
            }
            if (clubService == null)
            {
                clubService = new ClubService();
            }

            IList<Vak> thuisVakken = vakService.GetThuisVakkeninStadion(clubOverview.Stadionid).ToList();

            vakService.BerekenAbonnementPrijzenBijVakken(thuisVakken, clubService.GetClub(clubOverview.GekozenClubId));

            // Lijst voor aantal tickets
            List<SelectListItem> list = new List<SelectListItem>
            {
                new SelectListItem { Text = "1", Value = "1", Selected = true },
                new SelectListItem { Text = "2", Value = "2" },
                new SelectListItem { Text = "3", Value = "3" },
                new SelectListItem { Text = "4", Value = "4" }
            };

            // ViewModel aanmaken en opvullen
            AbonnementBuy abonnementBuy = new AbonnementBuy()
            {
                PloegId = clubOverview.GekozenClubId,
                PloegNaam = clubOverview.GekozenClubNaam,
                Logo = clubOverview.Logo,
                Stadionid = clubOverview.Stadionid,
                StadionNaam = clubOverview.StadionNaam,
                Vakken = thuisVakken,
                HoeveelheidAbonnementenList = list

            };
            return View(abonnementBuy);
        }
    }
}

VoetbalTicketStore/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    public class ClubController : BaseController
    {
        private ClubService clubService;

        // GET: Club
        public ActionResult Index()
        {
            clubService = new ClubService();
            var clubs = clubService.All();

            // ViewModel aanmaken en opvullen
            ClubOverview clubOverview = new ClubOverview()
            {
                Clubs = clubService.All().ToList()
            };


            // we geven de lijst met clubs mee aan de view
            return View(clubOverview);
        }
    }
}

VoetbalTicketStore/Controllers/WedstrijdController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;

namespace VoetbalTicketStore.Controllers
{
    public class WedstrijdController : BaseController
    {

        IWedstrijdService wedstrijdService;


        public WedstrijdController()
        {

        }

        public WedstrijdController(IWedstrijdService wedstrijdService)
        {
            this.wedstrijdService = wedstrijdService;
        }



        // GET: Wedstrijd
        public ActionResult Index()
        {
            if(wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            var wedstrijden = wedstrijdService.GetUpcomingWedstrijden();
            // we geven de lijst met wedstrijden mee aan de view
            return View(wedstrijden);
        }

        public ActionResult WedstrijdKalender(Club club)
        {
            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            var wedstrijden = wedstrijdService.GetWedstrijdKalenderVanPloeg(club);
            return View(wedstrijden);
        }
    }
}

VoetbalTicketStore/Views/Club/Index.cshtml
@model VoetbalTicketStore.ViewModel.ClubOverview
@{
    ViewBag.Title = "Clubs";
}
<div class="page-header">
    <h1>Clubs <small>Onze competitie</small></h1>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.Clubs)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.Logo)

        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.StadionNaam)

        </th>
        <th>
            Abonnementen
        </th>
        <th>
            Wedstrijdkalender
        </th>
    </tr>

    @foreach (var item in Model.Clubs)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @{
                    var imagePath = "/Content/img/clublogo/placeholder.png";
                    if (item.Logo != null)
                    {
                        imagePath = item.Logo;
                    }
                    <img src="@imagePath" alt="logo" style="width:30%;"/>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stadion.Naam)
            </td>
            <td>
                @Html.ActionLink("Koop abonnement", "Buy", "Abonnement", new { GekozenClubId = item.Id, GekozenClubNaam = item.Naam, Logo = imagePath, StadionId = item.Stadionid, StadionNaam = item.Stadion.Naam }, null)
            </td>
            <td>
                @*Notice that you specify the controller name without the Controller suffix.*@
                @*Dit werkt wegens de RouteConfig defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
                *@

                @Html.ActionLink("Toon Wedstrijdkalender", "WedstrijdKalender", "Wedstrijd", new { item.Id }, null)
            </td>
        </tr>
    }

</table>