VoetbalTicketStore/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    public class ClubController : BaseController
    {
        private ClubService clubService;

        // GET: Club
        public ActionResult Index()
        {
            clubService = new ClubService();
            var clubs = clubService.All();

            // ViewModel aanmaken en opvullen
            ClubOverview clubOverview = new ClubOverview()
            {
                Clubs = clubService.All().ToList()
            };


            // we geven de lijst met clubs mee aan de view
            return View(clubOverview);
        }
    }
}

VoetbalTicketStore/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Helpers;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    public class HomeController : BaseController
    {

        private IWedstrijdService wedstrijdService;
        private UserManager<ApplicationUser> userManager;
        private IBestellingService bestellingService;

        public HomeController()
        {

        }

        public HomeController(IWedstrijdService wedstrijdService, UserManager<ApplicationUser> userManager, IBestellingService bestellingService)
        {
            this.wedstrijdService = wedstrijdService;
            this.userManager = userManager;
            this.bestellingService = bestellingService;
        }


        public async Task<ViewResult> Index()
        {
            if (userManager == null)
            {
                userManager = new UserManager<ApplicationUser>(
               new UserStore<ApplicationUser>(
                   new ApplicationDbContext()));
            }

            // Find user
            var user = await userManager.FindByIdAsync(User.Identity.GetUserId());

            // get aangeraden wedstrijden

            if (wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }

            // viewmodel opvullen
            HomeVM homeVM = new HomeVM();

            if (user != null)
            {
                if (Session["ShoppingCartItemTotal"] == null)
                {
                    if (bestellingService == null)
                    {
                        bestellingService = new BestellingService();
                        Bestelling bestelling = bestellingService.FindOpenstaandeBestellingDoorUser(user.Id);
                        if (bestelling != null)
                        {
                            int totaalAantalitems = 0;
                            foreach (ShoppingCartData s in bestelling.ShoppingCartDatas)
                            {
                                totaalAantalitems += s.Hoeveelheid;
                            }
                            if (totaalAantalitems > 0)
                            {
                                Session["ShoppingCartItemTotal"] = totaalAantalitems;
                            }
                            else
                            {
                                Session["ShoppingCartItemTotal"] = null;
                            }
                        }
                    }
                }

                // opgehaalde lijst verandert normaal niet snel, wordt tijdelijk in de session opgeslagen om het aantal SQL-queries te beperken
                List<Wedstrijd> list = (List<Wedstrijd>)Session["AanTeRadenWedstrijden"];
                if (list == null)
                {
                    homeVM.HighlightList = wedstrijdService.GetAanTeRadenWedstrijdenVoorClub(user.FavorietTeam, 3).ToList();
                    Session["AanTeRadenWedstrijden"] = homeVM.HighlightList;
                }
                else
                {
                    homeVM.HighlightList = list;
                }
            }

            return View(homeVM);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        // Culture-cookie instellen
        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            // Save culture in a cookie
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

VoetbalTicketStore/Controllers/StadionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.Service.Interfaces;

namespace VoetbalTicketStore.Controllers
{
    public class StadionController : BaseController
    {
        private IStadionService stadionService;

        public StadionController()
        {

        }

        public StadionController(IStadionService stadionService)
        {
            this.stadionService = stadionService;
        }

        // GET: Stadion
        public ActionResult Index()
        {
            if (stadionService == null)
            {
                stadionService = new StadionService();
            }
            IEnumerable<Stadion> stadia = stadionService.All();

            return View(stadia);
        }
    }
}

VoetbalTicketStore/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;
using VoetbalTicketStore.Service.Interfaces;
using VoetbalTicketStore.ViewModel;

namespace VoetbalTicketStore.Controllers
{
    [Authorize]
    public class TicketController : BaseController
    {

        private IWedstrijdService wedstrijdService;
        private IVakService vakService;

        public TicketController()
        {

        }

        public TicketController(IWedstrijdService wedstrijdService, IVakService vakService)
        {
            this.wedstrijdService = wedstrijdService;
            this.vakService = vakService;
        }

        // GET: Ticket
        public ActionResult Buy(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Wedstrijd ophalen
            if (wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            Wedstrijd wedstrijd = wedstrijdService.GetWedstrijdById(id);

            // Vakken ophalen van stadion

            if (vakService == null)
            {
                vakService = new VakService();
            }

            IEnumerable<Vak> vakken = vakService.GetVakkenInStadion(wedstrijd.Stadionid);

            // Prijzen bepalen per vak (thuisploeg)
            vakService.BerekenPrijzenBijVakken(vakken, wedstrijd.Club);

            // Vrije plaatsen bepalen per vak
            vakService.BerekenAantalVrijePlaatsen(vakken, wedstrijd, wedstrijd.Club);

            // ViewModel maken en opvullen
            TicketWedstrijd ticketWedstrijd = new TicketWedstrijd
            {
                Wedstrijd = wedstrijd,
                Stadion = wedstrijd.Stadion,
                Thuisploeg = wedstrijd.Club,
                Tegenstanders = wedstrijd.Club1,
                VakkenList = vakken
            };

            return View(ticketWedstrijd);
        }

        // POST: Confirm
        [HttpPost]
        public ActionResult Confirm(int vakId, int aantalVrijePlaatsen, decimal prijs, int wedstrijdId, int thuisploegId, int bezoekersId, string vakNaam)
        {

            if (vakId < 0 || aantalVrijePlaatsen < 0 || prijs < 0 || wedstrijdId < 0 || thuisploegId < 0 || bezoekersId < 0 || vakNaam == null || vakNaam.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            // Lijst voor aantal tickets
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "1", Value = "1", Selected = true });
            list.Add(new SelectListItem { Text = "2", Value = "2" });
            list.Add(new SelectListItem { Text = "3", Value = "3" });
            list.Add(new SelectListItem { Text = "4", Value = "4" });

            // ViewModel maken en opvullen
            TicketConfirm ticketConfirm = new TicketConfirm()
            {
                AantalVrijePlaatsen = aantalVrijePlaatsen,
                Prijs = prijs,
                HoeveelheidTicketsList = list,
                VakId = vakId,
                VakNaam = vakNaam,
                WedstrijdId = wedstrijdId,
                ThuisploegId = thuisploegId,
                BezoekersId = bezoekersId
            };

            return PartialView(ticketConfirm);
        }
    }
}

VoetbalTicketStore/Controllers/WedstrijdController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoetbalTicketStore.Models;
using VoetbalTicketStore.Service;

namespace VoetbalTicketStore.Controllers
{
    public class WedstrijdController : BaseController
    {

        IWedstrijdService wedstrijdService;


        public WedstrijdController()
        {

        }

        public WedstrijdController(IWedstrijdService wedstrijdService)
        {
            this.wedstrijdService = wedstrijdService;
        }



        // GET: Wedstrijd
        public ActionResult Index()
        {
            if(wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            var wedstrijden = wedstrijdService.GetUpcomingWedstrijden();
            // we geven de lijst met wedstrijden mee aan de view
            return View(wedstrijden);
        }

        public ActionResult WedstrijdKalender(Club club)
        {
            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (wedstrijdService == null)
            {
                wedstrijdService = new WedstrijdService();
            }
            var wedstrijden = wedstrijdService.GetWedstrijdKalenderVanPloeg(club);
            return View(wedstrijden);
        }
    }
}

VoetbalTicketStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "Over ons";
}
<div class="page-header">
    <h1>Over ons <small>Wie, wat waar?</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Voorstelling</h2>
        <p>
            Dit is de officiële website van de Belgische eerste voetbalklasse. Dit is de hoogste afdeling van het Belgisch profvoetbal, bestaande uit 16 teams. De sponsornaam is Jupiler Pro League, naar de huidige hoofdsponsor Jupiler en organisator Pro League. De Belgische competitie startte in 1895 en is daarmee de oudste op het Europese vasteland.
        </p>
        <h2>Wat?</h2>
        <p>
            De competitie start eind juli en eindigt in de tweede helft van mei. In de wintermaanden wordt er, sinds de competitiehervorming in 2009, kerstvoetbal georganiseerd: er wordt een speeldag afgewerkt op tweede en derde kerstdag. Sinds die hervorming telt de competitie zestien clubs. Elke ploeg speelt tweemaal (heen en terug) tegen elk van de vijftien andere, dus 30 wedstrijden in totaal. Na de reguliere competitie worden er play-offs afgewerkt, waarbij de zes hoogst gerangschikte clubs het nogmaals twee keer tegen elkaar opnemen (heen en terug) in play-off 1. Dit betekent dat de top zes in totaal 40 wedstrijden afwerkt, waarvan 30 in de reguliere competitie en tien in de play-offs. Bij de start van play-off 1 wordt het puntenaantal, dat de deelnemende ploegen in de reguliere competitie hebben behaald, gedeeld door twee en naar boven afgerond. De ploegen herbeginnen dus niet vanaf nul punten.
        </p><p>
            De nummers zeven tot en met vijftien worden, samen met de drie hoogst gerangschikte clubs uit eerste klasse B (met uitzondering van de kampioen) verdeeld in twee poules van elk zes teams. Ook zij nemen het nog tweemaal tegen elkaar op (heen en terug), waardoor ook zij 40 wedstrijden afwerken, 30 in de competitie en tien tijdens de play-offs. In tegenstelling tot play-off 1 starten de teams uit play-off 2 wel vanaf nul, er wordt dus geen rekening meer gehouden met het puntenaantal uit de reguliere competitie.
        </p>
        <p> Zowel de competitie als de play-offs worden gespeeld volgens het driepuntensysteem.</p>
        <p>
            Afhankelijk van hoe goed de Belgische ploegen in Europees verband presteren, wordt bepaald hoeveel clubs in de Champions League of de UEFA Europa League mogen meedingen. Door de huidige UEFA-coëfficiënt kwalificeren de kampioen en de vice-kampioen van de Belgische competitie (m.a.w. het nummer één en twee uit play-off I) zich voor de Champions League. Meestal (afhankelijk van de coëfficiënt) is de kampioen rechtstreeks geplaatst voor de groepsfase en moet de vicekampioen twee voorrondes afwerken. De winnaar van de beker gaat rechtstreeks naar de groepsfase van de Europa League en de winnaar van de reguliere competitie mag deelnemen aan de voorlaatste voorronde. Indien die laatste zich echter kwalificeert voor de Champions League, dan krijgt het nummer drie uit play-off 1 het Europa League-ticket voor de voorlaatste voorronde (tenzij het nummer drie ook de bekerwinnaar is, dan krijgt de vierde dit Europese ticket). Indien de bekerwinnaar zich kwalificeert voor de Champions League, gaat het ticket voor de groepsfase van de Europa League naar de derde in play-off 1. Indien een ploeg uit de top drie dan ook de reguliere competitie zou hebben gewonnen, krijgt de vierde het ticket voor de voorlaatste voorronde van de Europa League. Indien een ploeg zowel de reguliere competitie als de beker wint, maar niet in de top drie van play-off 1 eindigt, dan krijgt het nummer drie het ticket voor de voorlaatste voorronde van de Europa League.
        </p>
        <h2>Waar?</h2>
        <p>Zestien clubs spelen in 2017/18 in eerste klasse A. Elf clubs komen uit Vlaanderen, vier clubs komen uit Wallonië en één uit Brussel. <strong>Deze website biedt voorlopig enkel de top 6 van de competitie!</strong> </p>
    </div>
</div>

VoetbalTicketStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VoetbalTicketStore/Views/Home/Index.cshtml
@model VoetbalTicketStore.ViewModel.HomeVM

@{
    ViewBag.Title = "Startpagina";
}



<div class="jk-slider">
    <div id="carousel-example" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">

            @if (Model.HighlightList != null)
            {
                <li data-target="#carousel-example" data-slide-to="0" class="active"></li>

                //met default slide
                if (Model.HighlightList.Count < 3)
                {
                    for (int i = 0; i < Model.HighlightList.Count(); i++)
                    {
                        <li data-target="#carousel-example" data-slide-to=@(i+1)></li>
                    }
                }

                //zonder default slide - andere manier van tellen
                else
                {
                    for (int i = 1; i < Model.HighlightList.Count(); i++)
                    {
                        <li data-target="#carousel-example" data-slide-to=@(i)></li>
                    }
                }
            }


        </ol>
        <div class="carousel-inner">

            @*Geen favorieten of minder dan 3 -> voeg een default slide in.*@
            @if (Model.HighlightList == null || Model.HighlightList.Count() < 3)
            {
                <div class="item active">
                    <div class="hero">
                        <h1>Welkom!</h1>
                        <h2>Koop uw voetbaltickets hier!</h2>
                        @Html.ActionLink("Koop tickets", "Index", "Wedstrijd", new { }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                    </div>
                    <div class="overlay"></div>
                    <img src="~/Content/img/wedstrijd-placeholder.JPG" />
                </div>
            }

            @if (Model.HighlightList != null && Model.HighlightList.Count() > 0)
            {
                for (var i = 0; i < Model.HighlightList.Count(); i++)
                {
                    if (Model.HighlightList.Count == 3 && i == 0)
                    {
                        @:<div class="item active">
                        }
                        else
                        {
                            @:<div class="item">
                            }
                            <div class="hero">
                                <h4>@Html.DisplayFor(modelItem => modelItem.HighlightList[i].DatumEnTijd)</h4>
                                <h1>@Html.DisplayFor(modelItem => modelItem.HighlightList[i].Club.Naam) - @Html.DisplayFor(modelItem => modelItem.HighlightList[i].Club1.Naam)</h1>
                                @if (Model.HighlightList[i].Beschrijving != null)
                                {
                                    <h2>@Html.DisplayFor(modelItem => modelItem.HighlightList[i].Beschrijving)  </h2>
                                }
                                else
                                {
                                    <h2>Aangeraden voor jou!</h2>
                                }
                                @Html.ActionLink("Koop tickets", "Buy", "Ticket", new { id = Model.HighlightList[i].Id }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                            </div>
                            <div class="overlay"></div>
                            if (Model.HighlightList[i].Afbeelding != null)
                            {
                                <a href="/Ticket/Buy/Model.HighlightList[i].Id"><img src=@Model.HighlightList[i].Afbeelding alt="Afbeelding"></a>
                            }
                            else
                            {
                                <img src="~/Content/img/wedstrijd-placeholder.JPG" />
                            }
                        @:</div>
                    }
                }
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Wedstrijdkalender</h2>
        <p>
            Wedstrijdje meepikken? Bekijk ze allemaal!
        </p>
        <p>
            <a href="@Url.Action("Index", "Wedstrijd")" class="btn btn-default">
                Kalender
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
            </a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Stadions</h2>
        <p>Waar speelt uw favoriete ploeg? Bekijk het hier!</p>
        <p>
            <a href="@Url.Action("Index", "Stadion")" class="btn btn-default">
                Stadions
                <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
            </a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Clubs</h2>
        <p>Onze Belgische competitie, soms bitsig, maar vooral charmant!</p>
        <p>
            <a href="@Url.Action("Index", "Club")" class="btn btn-default">
                Clubs
                <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
            </a>
        </p>
    </div>
</div>